apiVersion: v1
kind: Service
metadata:
  name: vidsnap-worker-video-service
  labels:
    run: vidsnap-worker-video-service
spec:
  selector:
    app: vidsnap-worker-video-pod
  ports:
  - name: port8080  
    port: 8080    
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer